import type { Lead, Activity, Reminder } from './types'
import { generateId } from './storage'

function daysAgo(n: number): string {
  const d = new Date()
  d.setDate(d.getDate() - n)
  return d.toISOString()
}

function daysFromNow(n: number): string {
  const d = new Date()
  d.setDate(d.getDate() + n)
  return d.toISOString().split('T')[0]
}

export function buildSampleData(): { leads: Lead[]; activities: Activity[]; reminders: Reminder[] } {
  const leads: Lead[] = [
    {
      id: 'lead_001',
      name: 'John & Lisa Smith',
      email: 'jsmith@gmail.com',
      phone: '(732) 555-0101',
      address: '14 Oak Ridge Dr',
      city: 'Howell',
      state: 'NJ',
      source: 'referral',
      projectType: 'shower-doors',
      projectDetails: 'Frameless shower enclosure, master bath. ~60" x 34" alcove. Client wants low iron glass.',
      estimatedValue: 3200,
      status: 'quoted',
      assignedTo: 'EJ',
      priority: 'high',
      createdAt: daysAgo(12),
      updatedAt: daysAgo(3),
      nextFollowUp: daysFromNow(1),
      tags: ['residential', 'low-iron'],
    },
    {
      id: 'lead_002',
      name: 'Premier Fitness Howell',
      email: 'manager@premierfitness.com',
      phone: '(732) 555-0202',
      address: '888 Route 9',
      city: 'Howell',
      state: 'NJ',
      source: 'phone',
      projectType: 'mirrors',
      projectDetails: 'Full mirror wall for new gym expansion. Two walls 20ft x 8ft. Need clips + safety backing.',
      estimatedValue: 8500,
      status: 'consultation',
      assignedTo: 'EJ',
      priority: 'high',
      createdAt: daysAgo(5),
      updatedAt: daysAgo(1),
      nextFollowUp: daysFromNow(2),
      tags: ['commercial', 'large-project'],
    },
    {
      id: 'lead_003',
      name: 'Carlos & Ana Rivera',
      email: 'crivera@outlook.com',
      phone: '(908) 555-0303',
      address: '55 Birchwood Ln',
      city: 'Freehold',
      state: 'NJ',
      source: 'website',
      projectType: 'railings',
      projectDetails: 'Deck glass railing replacement, approx 40 linear ft. Second story deck. Post system preferred.',
      estimatedValue: 6800,
      status: 'new',
      assignedTo: 'Mike',
      priority: 'medium',
      createdAt: daysAgo(2),
      updatedAt: daysAgo(2),
      nextFollowUp: daysFromNow(1),
      tags: ['residential', 'deck'],
    },
    {
      id: 'lead_004',
      name: 'The Waterford Luxury Condos',
      email: 'development@waterfordliving.com',
      phone: '(201) 555-0404',
      address: '200 Harbor Blvd',
      city: 'Weehawken',
      state: 'NJ',
      source: 'contractor',
      projectType: 'exterior',
      projectDetails: 'Curtain wall system for 8-story mixed-use building. Working with GC Pinnacle Construction. Bid due next month.',
      estimatedValue: 185000,
      status: 'consultation',
      assignedTo: 'EJ',
      priority: 'high',
      createdAt: daysAgo(18),
      updatedAt: daysAgo(4),
      nextFollowUp: daysFromNow(3),
      tags: ['commercial', 'big-fish', 'GC-partner'],
    },
    {
      id: 'lead_005',
      name: 'Jennifer Williams',
      email: 'jenw84@gmail.com',
      phone: '(732) 555-0505',
      address: '7 Maple Court',
      city: 'Jackson',
      state: 'NJ',
      source: 'referral',
      projectType: 'shower-doors',
      projectDetails: 'Neo-angle frameless enclosure for guest bath. Referred by John Smith (lead_001). Chrome hardware.',
      estimatedValue: 2400,
      status: 'followup',
      assignedTo: 'EJ',
      priority: 'medium',
      createdAt: daysAgo(21),
      updatedAt: daysAgo(6),
      nextFollowUp: daysFromNow(0),
      tags: ['residential', 'referral-smith'],
    },
    {
      id: 'lead_006',
      name: 'Prestige Restaurant Group',
      email: 'ops@prestigegroup.com',
      phone: '(973) 555-0606',
      address: '1450 Morris Ave',
      city: 'Union',
      state: 'NJ',
      source: 'social',
      projectType: 'office',
      projectDetails: 'Glass partition walls for new restaurant corporate office. ~300 sq ft of partitions. Frosted bottom panels.',
      estimatedValue: 14000,
      status: 'quoted',
      assignedTo: 'Mike',
      priority: 'high',
      createdAt: daysAgo(30),
      updatedAt: daysAgo(8),
      nextFollowUp: daysFromNow(-2),
      tags: ['commercial', 'corporate'],
    },
    {
      id: 'lead_007',
      name: 'Tom & Karen Anderson',
      email: 'tanderson@comcast.net',
      phone: '(732) 555-0707',
      address: '28 Hillcrest Ave',
      city: 'Tinton Falls',
      state: 'NJ',
      source: 'referral',
      projectType: 'shower-doors',
      projectDetails: 'Master bath frameless shower door. 3-panel bypass. Brushed nickel hardware. Project confirmed.',
      estimatedValue: 2800,
      status: 'won',
      assignedTo: 'EJ',
      priority: 'medium',
      createdAt: daysAgo(45),
      updatedAt: daysAgo(5),
      nextFollowUp: null,
      tags: ['residential', 'won'],
    },
    {
      id: 'lead_008',
      name: 'Rachel Thompson',
      email: 'rthompson@yahoo.com',
      phone: '(848) 555-0808',
      address: '92 Sunset Blvd',
      city: 'Toms River',
      state: 'NJ',
      source: 'website',
      projectType: 'backsplash',
      projectDetails: 'Kitchen backsplash, full-height behind range + sides. About 25 sq ft. White subway glass tiles.',
      estimatedValue: 1800,
      status: 'lost',
      assignedTo: 'Sarah',
      priority: 'low',
      createdAt: daysAgo(60),
      updatedAt: daysAgo(20),
      nextFollowUp: null,
      tags: ['residential'],
      lostReason: 'Went with tile contractor — decided against glass',
    },
    {
      id: 'lead_009',
      name: 'Dr. Mark Patel',
      email: 'mpatel@pateldental.com',
      phone: '(732) 555-0909',
      address: '330 Professional Plaza',
      city: 'Marlboro',
      state: 'NJ',
      source: 'contractor',
      projectType: 'office',
      projectDetails: 'Dental office renovation — glass reception desk enclosure + two glass partition offices. Modern look, frosted band.',
      estimatedValue: 9500,
      status: 'new',
      assignedTo: 'EJ',
      priority: 'high',
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
      nextFollowUp: daysFromNow(2),
      tags: ['commercial', 'medical'],
    },
    {
      id: 'lead_010',
      name: 'Melissa & Derek Cho',
      email: 'dcho@gmail.com',
      phone: '(201) 555-1010',
      address: '6 Creekside Dr',
      city: 'Bridgewater',
      state: 'NJ',
      source: 'social',
      projectType: 'mirrors',
      projectDetails: 'Master bedroom full-wall mirror, ~12ft wide x 9ft tall. Frameless with J-channel. They are also interested in a dining room mirror.',
      estimatedValue: 4200,
      status: 'followup',
      assignedTo: 'Sarah',
      priority: 'medium',
      createdAt: daysAgo(14),
      updatedAt: daysAgo(7),
      nextFollowUp: daysFromNow(-1),
      tags: ['residential'],
    },
  ]

  const activities: Activity[] = [
    // John & Lisa Smith (lead_001)
    {
      id: generateId(),
      leadId: 'lead_001',
      type: 'call',
      description: 'Spoke with Lisa. She loved the low iron glass sample. Wants to see chrome vs brushed nickel hardware in person.',
      createdAt: daysAgo(3),
      createdBy: 'EJ',
    },
    {
      id: generateId(),
      leadId: 'lead_001',
      type: 'measurement',
      description: 'Measurements taken. 60.25" x 34.5" alcove. Verified drain location. Noted there\'s a niche we need to work around.',
      createdAt: daysAgo(10),
      createdBy: 'Mike',
    },
    {
      id: generateId(),
      leadId: 'lead_001',
      type: 'quote',
      description: 'Sent quote #Q-2024-0312 via email. $3,200 includes low iron glass, chrome hardware, installation.',
      createdAt: daysAgo(8),
      createdBy: 'EJ',
    },
    // Premier Fitness (lead_002)
    {
      id: generateId(),
      leadId: 'lead_002',
      type: 'visit',
      description: 'Site visit with gym manager Dave. Measured two walls. Confirmed they want safety backing. They\'re planning a grand reopening in 6 weeks.',
      createdAt: daysAgo(1),
      createdBy: 'EJ',
    },
    {
      id: generateId(),
      leadId: 'lead_002',
      type: 'call',
      description: 'Initial inquiry call. Dave said they got our number from a contractor. Big project — treat as priority.',
      createdAt: daysAgo(5),
      createdBy: 'EJ',
    },
    // Waterford Condos (lead_004)
    {
      id: generateId(),
      leadId: 'lead_004',
      type: 'note',
      description: 'GC contact is Alex Novak at Pinnacle Construction. Main contact on client side is Sarah Weston VP Development.',
      createdAt: daysAgo(18),
      createdBy: 'EJ',
    },
    {
      id: generateId(),
      leadId: 'lead_004',
      type: 'visit',
      description: 'Met with architect and GC on site. Building plans reviewed. We need to finalize our scope with structural engineer.',
      createdAt: daysAgo(10),
      createdBy: 'EJ',
    },
    {
      id: generateId(),
      leadId: 'lead_004',
      type: 'call',
      description: 'Follow-up with Alex. Bid deadline pushed to end of month. Asked us to include breakdown by floor.',
      createdAt: daysAgo(4),
      createdBy: 'EJ',
    },
    // Jennifer Williams (lead_005)
    {
      id: generateId(),
      leadId: 'lead_005',
      type: 'call',
      description: 'Reached out twice — no answer. Left voicemail. She was referred by John Smith.',
      createdAt: daysAgo(6),
      createdBy: 'EJ',
    },
    {
      id: generateId(),
      leadId: 'lead_005',
      type: 'text',
      description: 'Texted her our gallery link and mentioned we just finished her neighbor\'s shower. She replied that she\'s very interested.',
      createdAt: daysAgo(6),
      createdBy: 'EJ',
    },
    // Prestige Restaurant (lead_006)
    {
      id: generateId(),
      leadId: 'lead_006',
      type: 'quote',
      description: 'Sent quote #Q-2024-0298. $14,000 for full partition system with frosted lower panels. They are comparing 2 other bids.',
      createdAt: daysAgo(15),
      createdBy: 'Mike',
    },
    {
      id: generateId(),
      leadId: 'lead_006',
      type: 'call',
      description: 'Spoke with their ops manager. They are reviewing quotes this week. Mentioned our timeline could be a deciding factor.',
      createdAt: daysAgo(8),
      createdBy: 'Mike',
    },
    // Tom Anderson (lead_007) - WON
    {
      id: generateId(),
      leadId: 'lead_007',
      type: 'call',
      description: 'Tom confirmed the job! Deposit received. Scheduling install for next available slot.',
      createdAt: daysAgo(5),
      createdBy: 'EJ',
    },
    {
      id: generateId(),
      leadId: 'lead_007',
      type: 'note',
      description: 'Installation scheduled for next Thursday. Mike on install. Tom wants a call day before to confirm arrival time.',
      createdAt: daysAgo(5),
      createdBy: 'EJ',
    },
    // Melissa & Derek Cho (lead_010)
    {
      id: generateId(),
      leadId: 'lead_010',
      type: 'call',
      description: 'Called Derek — he\'s interested but said wife is decision maker. Said to call back this weekend.',
      createdAt: daysAgo(7),
      createdBy: 'Sarah',
    },
    // Dr. Patel (lead_009)
    {
      id: generateId(),
      leadId: 'lead_009',
      type: 'call',
      description: 'Initial call from contractor Jake M. Dr. Patel is building out a new office and wants a premium glass look. Very motivated buyer.',
      createdAt: daysAgo(1),
      createdBy: 'EJ',
    },
  ]

  const reminders: Reminder[] = [
    {
      id: generateId(),
      leadId: 'lead_001',
      leadName: 'John & Lisa Smith',
      title: 'Call Lisa — they\'re deciding this week. Ask if they\'re ready to move forward.',
      dueDate: daysFromNow(1),
      assignedTo: 'EJ',
      completed: false,
      createdAt: daysAgo(3),
    },
    {
      id: generateId(),
      leadId: 'lead_002',
      leadName: 'Premier Fitness Howell',
      title: 'Send formal quote for mirror wall. They need it ASAP for budget approval.',
      dueDate: daysFromNow(0),
      assignedTo: 'EJ',
      completed: false,
      createdAt: daysAgo(1),
    },
    {
      id: generateId(),
      leadId: 'lead_003',
      leadName: 'Carlos & Ana Rivera',
      title: 'Call Carlos to schedule measurement visit for deck railing.',
      dueDate: daysFromNow(1),
      assignedTo: 'Mike',
      completed: false,
      createdAt: daysAgo(2),
    },
    {
      id: generateId(),
      leadId: 'lead_004',
      leadName: 'The Waterford Luxury Condos',
      title: 'Finalize curtain wall bid and send to Alex Novak at Pinnacle. Deadline is end of month.',
      dueDate: daysFromNow(3),
      assignedTo: 'EJ',
      completed: false,
      createdAt: daysAgo(4),
    },
    {
      id: generateId(),
      leadId: 'lead_005',
      leadName: 'Jennifer Williams',
      title: 'Call Jennifer — overdue follow-up on neo-angle shower. She said she was interested.',
      dueDate: daysFromNow(0),
      assignedTo: 'EJ',
      completed: false,
      createdAt: daysAgo(6),
    },
    {
      id: generateId(),
      leadId: 'lead_006',
      leadName: 'Prestige Restaurant Group',
      title: 'Follow up on quote for office partitions — they were reviewing bids this week.',
      dueDate: daysFromNow(-2),
      assignedTo: 'Mike',
      completed: false,
      createdAt: daysAgo(8),
    },
    {
      id: generateId(),
      leadId: 'lead_009',
      leadName: 'Dr. Mark Patel',
      title: 'Call Dr. Patel directly to introduce ourselves and schedule site visit.',
      dueDate: daysFromNow(2),
      assignedTo: 'EJ',
      completed: false,
      createdAt: daysAgo(1),
    },
    {
      id: generateId(),
      leadId: 'lead_010',
      leadName: 'Melissa & Derek Cho',
      title: 'Call Melissa (not Derek) about the bedroom mirror wall — she is the decision maker.',
      dueDate: daysFromNow(-1),
      assignedTo: 'Sarah',
      completed: false,
      createdAt: daysAgo(7),
    },
  ]

  return { leads, activities, reminders }
}
